format = """
$directory\
$git_branch\
$git_commit\
$git_status\
$git_state\
${custom.sesh}\
$battery\
$rust\
$lua\
$python\
$nodejs\
$c\
$fill\ 
$git_metrics\
$sudo\
$hostname\
$line_break\
$jobs\
${custom.vi_mode}
"""
# $character\

"$schema" = 'https://starship.rs/config-schema.json'

[hostname]
format = '[$ssh_symbol]($style)'
ssh_symbol = ''

[sudo]
disabled = false
symbol = '󱥠'
format = '[$symbol]($style)'

[fill]
symbol = ' '

[[battery.display]]
threshold = 40

[git_metrics]
disabled = false
only_nonzero_diffs = true

[rust]
style = 'red'
format = '[$symbol]($style) '
symbol = ""

[lua]
style = 'blue'
format = '[$symbol]($style) '
symbol = '󰢱 '

[nodejs]
style = 'green'
format = '[$symbol]($style) '

[c]
style = '149'
format = '[$symbol]($style) '

[python]
style = 'yellow'
format = '[$symbol]($style) '

[custom.vim]
style = '#5de4c7'
command = "echo 'nvim'"
when = ''' test "$NVIM" != "" '''

[custom.sesh]
style = '#5de4c7'
command = "echo $SESH_NAME"
when = ''' test "$SESH_NAME" != "" '''
format = '\[[$output]($style)\]'

[custom.vi_mode]
command = "echo $ZVM_MODE_PROMPT"
when = ''' test "$ZVM_MODE_PROMPT" != "" '''
format = '$output '

[character]
disabled = false
success_symbol = "[->](green)"
error_symbol = "[->](red)"
vimcmd_symbol = "[<-](green)"
vimcmd_visual_symbol = "[<-](yellow)"

[git_branch]
style = '#89ddff'
format = 'on [$symbol](#8da3bf)[$branch(:$remote_branch)]($style)'
only_attached = true

[git_commit]
style = '#89ddff'

[git_status]
style = '#91b4d5'
conflicted = '='
ahead = '⇡'
behind = '⇣'
diverged = '⇕ $ahead_count$behind_count'
up_to_date = ''
untracked = '?'
stashed = '\$'
modified = '!'
renamed = '»'
deleted = '✘'
format = '[$all_status$ahead_behind]($style) '

[username]
show_always = true
style_user = '#5de4c7'
style_root = 'red'

[directory]
truncation_length = 4
style = '#5de4c7'


[jobs]
style = 'blue'
disabled = false
symbol_threshold = 0

[line_break]
disabled = false
